-- Spring Security ACL Schema for H2 Database

-- Table: acl_sid
-- Stores security identities (principals/authorities)
CREATE TABLE IF NOT EXISTS acl_sid (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal BOOLEAN NOT NULL,
    sid VARCHAR(100) NOT NULL,
    CONSTRAINT unique_acl_sid UNIQUE(sid, principal)
);

-- Table: acl_class
-- Stores the domain object class names
CREATE TABLE IF NOT EXISTS acl_class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class VARCHAR(255) NOT NULL,
    class_id_type VARCHAR(255),
    CONSTRAINT unique_acl_class UNIQUE(class)
);

-- Table: acl_object_identity
-- Stores object identity information for domain objects
CREATE TABLE IF NOT EXISTS acl_object_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id_class BIGINT NOT NULL,
    object_id_identity VARCHAR(36) NOT NULL,
    parent_object BIGINT,
    owner_sid BIGINT,
    entries_inheriting BOOLEAN NOT NULL,
    CONSTRAINT unique_acl_object_identity UNIQUE(object_id_class, object_id_identity),
    CONSTRAINT fk_acl_object_identity_parent FOREIGN KEY (parent_object) REFERENCES acl_object_identity(id),
    CONSTRAINT fk_acl_object_identity_class FOREIGN KEY (object_id_class) REFERENCES acl_class(id),
    CONSTRAINT fk_acl_object_identity_owner FOREIGN KEY (owner_sid) REFERENCES acl_sid(id)
);

-- Table: acl_entry
-- Stores individual permission grants
CREATE TABLE IF NOT EXISTS acl_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acl_object_identity BIGINT NOT NULL,
    ace_order INTEGER NOT NULL,
    sid BIGINT NOT NULL,
    mask INTEGER NOT NULL,
    granting BOOLEAN NOT NULL,
    audit_success BOOLEAN NOT NULL,
    audit_failure BOOLEAN NOT NULL,
    CONSTRAINT unique_acl_entry UNIQUE(acl_object_identity, ace_order),
    CONSTRAINT fk_acl_entry_object FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity(id),
    CONSTRAINT fk_acl_entry_acl FOREIGN KEY (sid) REFERENCES acl_sid(id)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_acl_sid_sid ON acl_sid(sid);
CREATE INDEX IF NOT EXISTS idx_acl_class_class ON acl_class(class);
CREATE INDEX IF NOT EXISTS idx_acl_object_identity_object ON acl_object_identity(object_id_class, object_id_identity);
CREATE INDEX IF NOT EXISTS idx_acl_entry_object ON acl_entry(acl_object_identity);
